### ISSUE TITLE
Verbatim code chunks: keep grey background

### ISSUE THREAD

**Issue by dr-harper** [nathaneastwood/knitrhooks#11]
The current verbatim code setting works really well, but a minor issues I have with it is that it removes the shaded background for the code environment.

I was wondering if there was any way to make it keep the background area? The best way I know how to do this is [explained here](https://yihui.name/en/2017/11/knitr-verbatim-code-chunk/), where you wrap the code as follows:

`````
---
output:
  pdf_document: default
---


````md
```{r, eval=TRUE}`r ''`
1 + 1
```
````
`````

The disadvantage of this approach is that it will suppress the code from running, so there is a need to rerun the chunk again afterwards.

I feel there must be a way to adapt the existing verbatim function with some `gsub` to insert the correct formatting. 

May have time to dig into this in the near future!

**Comment by dr-harper** [comment]
See PR #12 for my version of the package. Tried to keep the syntax as consistent as possible with yours.

**Comment by nathaneastwood** [comment]
Excellent! I knew the colour shading was an issue but I didn’t have time to look into it. Does this still work when you use `eval = FALSE`? Because using that prints the verbatim code and removes the eval option from the verbatim (not at a computer to test at the moment).

**Comment by nathaneastwood** [comment]
Ah...apologies. I just read the file changes and it seems this is a different option to `source_verbatim`. I need to get to a computer to properly look at it but it looks good 🙂

**Comment by dr-harper** [comment]
Yeah, I added it as a separate function as I think they both could be useful in different scenarios. Will be using this in documents straight away so should be able to report back on how stable it is and make improvements if required.

**Comment by nathaneastwood** [comment]
Ok ideal. I’ll get to my computer tomorrow hopefully and take a look, if not, it’ll be Monday.

**Comment by dr-harper** [comment]
This currently doesn't do the syntax highlighting, but as far as I can tell this will be a hard one to get working/ is not possible.

This issue is related: https://github.com/yihui/knitr/issues/1237

**Comment by nathaneastwood** [comment]
Closed in https://github.com/nathaneastwood/knitrhooks/commit/8e22a96371eb73b581fcd949f06183ff7bfe391d

We just need to decide whether to retire `source_verbatim` or not.
