### ISSUE TITLE
Setting output_max_height changes options in other chunks

### ISSUE THREAD

**Issue by jonocarroll** [nathaneastwood/knitrhooks#14]
On trying this package with the `output_max_height()` option, I found that all of my outputs were screwed up, namely that they were no longer treated as outputs but inline HTML. 

Example:

````r
---
title: "test_knitrhooks"
author: "Jonathan Carroll"
date: "17/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
orig_output_hook <- knitr::knit_hooks$get("output")

library(knitrhooks)
output_max_height()
```

# Example document

```{r output_max_height = "300px"}
print(mtcars)
```

# Another section

```{r}
with(mtcars, table(cyl, am))
```

# Hooks need to be reset

```{r}
knitr::knit_hooks$set(output = orig_output_hook)
```

Then table returns to normal

```{r}
with(mtcars, table(cyl, am))
```
````

Produces the following:

![screen shot 2018-10-17 at 9 42 11 am](https://user-images.githubusercontent.com/9496865/47052835-b80d4100-d1f1-11e8-8b75-bc41f595968a.jpg)

It appears that the following chunk is being interpreted literally (as HTML) without a `<pre>` tag.

This change at least makes the other chunks behave as normal:

```r
output_max_height <- function() {
  knitr::knit_hooks$set(output = function(x, options) {
      if (!is.null(options$output_max_height)) {
        paste0("<pre style = \"max-height:", options$output_max_height, 
               "; float: left; width: 910px; overflow-y: auto;\">", 
               x, "</pre>")
      }
      else {
        paste0("<pre>", x, "</pre>") 
      }
  }) 
}
```

![screen shot 2018-10-17 at 10 27 49 am](https://user-images.githubusercontent.com/9496865/47054044-5d76e380-d1f7-11e8-910b-936b250c1c3a.jpg)

**Comment by nathaneastwood** [comment]
Good spot. Thanks for checking out the package...I really need to find time to add tests!
