### ISSUE TITLE
output_max_width chunks are not the same width as others

### ISSUE THREAD

**Issue by jonocarroll** [nathaneastwood/knitrhooks#15]
Perhaps setting the width as a fixed value is overzealous. This version (which includes the fix to #14) keeps the chunk the same size as the normal chunks

````r
knitr::knit_hooks$set(output = function(x, options) {
  if (!is.null(options$output_max_height)) {
    paste0("<pre style = \"max-height:", options$output_max_height, 
           "; overflow-y: auto;\">", 
           x, "</pre>")
  }
  else {
    paste0("<pre> ", x, "</pre>")
  }
})
````

**Comment by nathaneastwood** [comment]
This is a fair point. I could have sworn there was a reason for setting the width in my original code but it doesn't seem to affect much removing it.
